version: "3.9"
services:

  fastapi:
    build: ./app
    container_name: fastapi
    command: uvicorn app.main:app --host=localhost --reload
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8004:8000"
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/db
    depends_on:
      - db

  db:
    image: bitnami/postgresql
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}