version: "3.9"
services:

  web:
    build: ./app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8004:8000
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/foo
    depends_on:
      - db

  db:
    image: bitnami/postgresql
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}