version: "3.9"
services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  app:
    build: .
    container_name: app
    command: uvicorn main:app --host=0.0.0.0 --reload
    restart: always
    volumes:
      - .:/usr/src/
    ports:
      - "8000:8000"
    depends_on:
        - db